// ==========================================================
// ============  EVENTOS PARA MODO DECADE  ==================
// ==========================================================
//
// Categorías y sus iconos:
//   transfer  → 💰
//   trophy    → 🏆
//   debut     → 👶
//   retire    → 👋
//   award     → ⭐
//   milestone → 🎯
//   record    → 📜
//   drama     → 💔
//
// Total: 150 eventos (1957-2024)
// Bilingüe: text y description tienen { es, en }
// ==========================================================

const decadeEvents = [

    // ==================================================
    // ===== TRANSFERENCIAS 💰 (28 eventos) =============
    // ==================================================
    { id: "tr_neymar_psg", year: 2017, category: "transfer", text: { es: "Neymar ficha por el PSG por 222M€", en: "Neymar signs for PSG for €222M" }, description: { es: "El traspaso más caro de la historia. PSG paga la cláusula del brasileño al Barça.", en: "The most expensive transfer in history. PSG pays the Brazilian's release clause to Barça." } },
    { id: "tr_cr7_united", year: 2003, category: "transfer", text: { es: "Cristiano Ronaldo ficha por el Manchester United", en: "Cristiano Ronaldo signs for Manchester United" }, description: { es: "Con 18 años, deja el Sporting de Lisboa por 12M£.", en: "At 18, he leaves Sporting Lisbon for £12M." } },
    { id: "tr_zidane_madrid", year: 2001, category: "transfer", text: { es: "Zidane ficha por el Real Madrid", en: "Zidane signs for Real Madrid" }, description: { es: "Récord mundial de transferencia (75M€). Vino desde la Juventus.", en: "World transfer record (€75M). He came from Juventus." } },
    { id: "tr_mbappe_madrid", year: 2024, category: "transfer", text: { es: "Mbappé ficha por el Real Madrid", en: "Mbappé signs for Real Madrid" }, description: { es: "Llega libre tras 7 años en el PSG. Cumple su sueño de niño.", en: "He arrives on a free transfer after 7 years at PSG. Fulfilling his childhood dream." } },
    { id: "tr_messi_psg", year: 2021, category: "transfer", text: { es: "Messi ficha por el PSG", en: "Messi signs for PSG" }, description: { es: "Tras 21 años en el Barça, Messi se va por la imposibilidad de renovar.", en: "After 21 years at Barça, Messi leaves due to the impossibility of renewing." } },
    { id: "tr_beckham_madrid", year: 2003, category: "transfer", text: { es: "Beckham ficha por el Real Madrid", en: "Beckham signs for Real Madrid" }, description: { es: "El inglés deja el Manchester United y se une a los 'Galácticos'.", en: "The Englishman leaves Manchester United and joins the 'Galácticos'." } },
    { id: "tr_bale_madrid", year: 2013, category: "transfer", text: { es: "Bale ficha por el Real Madrid", en: "Bale signs for Real Madrid" }, description: { es: "100M€ desde el Tottenham, récord mundial en ese momento.", en: "€100M from Tottenham, a world record at the time." } },
    { id: "tr_messi_inter_miami", year: 2023, category: "transfer", text: { es: "Messi ficha por el Inter Miami", en: "Messi signs for Inter Miami" }, description: { es: "Tras dos años en PSG, Messi se va a la MLS estadounidense.", en: "After two years at PSG, Messi moves to the American MLS." } },
    { id: "tr_figo_madrid", year: 2000, category: "transfer", text: { es: "Figo ficha por el Real Madrid desde el Barça", en: "Figo signs for Real Madrid from Barça" }, description: { es: "El traspaso más polémico de la historia. Pérez paga 60M€ y desata la guerra culé-merengue.", en: "The most controversial transfer in history. Pérez pays €60M and unleashes the Barça-Madrid war." } },
    { id: "tr_ronaldo_madrid", year: 2002, category: "transfer", text: { es: "Ronaldo Nazário ficha por el Real Madrid", en: "Ronaldo Nazário signs for Real Madrid" }, description: { es: "El 'Fenómeno' llega desde el Inter para unirse a los Galácticos.", en: "The 'Phenomenon' arrives from Inter to join the Galácticos." } },
    { id: "tr_pogba_united", year: 2016, category: "transfer", text: { es: "Pogba vuelve al Manchester United desde la Juventus", en: "Pogba returns to Manchester United from Juventus" }, description: { es: "105M€, récord mundial. Volvía al club que lo había dejado salir gratis.", en: "€105M, a world record. He was returning to the club that had let him leave for free." } },
    { id: "tr_suarez_barca", year: 2014, category: "transfer", text: { es: "Luis Suárez ficha por el Barcelona", en: "Luis Suárez signs for Barcelona" }, description: { es: "Llega desde el Liverpool para formar la 'MSN' con Messi y Neymar.", en: "He arrives from Liverpool to form the 'MSN' trio with Messi and Neymar." } },
    { id: "tr_haaland_city", year: 2022, category: "transfer", text: { es: "Haaland ficha por el Manchester City", en: "Haaland signs for Manchester City" }, description: { es: "Llega desde el Borussia Dortmund por 60M€. Goleador histórico de la Premier en su 1ª temporada.", en: "He arrives from Borussia Dortmund for €60M. Historic Premier League goalscorer in his first season." } },
    { id: "tr_kaka_madrid", year: 2009, category: "transfer", text: { es: "Kaká ficha por el Real Madrid", en: "Kaká signs for Real Madrid" }, description: { es: "67M€ desde el AC Milan. Días después llegaría Cristiano Ronaldo.", en: "€67M from AC Milan. Days later Cristiano Ronaldo would arrive." } },
    { id: "tr_cruyff_barca", year: 1973, category: "transfer", text: { es: "Johan Cruyff ficha por el Barcelona", en: "Johan Cruyff signs for Barcelona" }, description: { es: "Desde el Ajax. Ese año el Barça gana la Liga tras 14 años sin hacerlo.", en: "From Ajax. That year Barça won the league after 14 years without doing so." } },
    { id: "tr_maradona_napoli", year: 1984, category: "transfer", text: { es: "Maradona ficha por el Nápoles", en: "Maradona signs for Napoli" }, description: { es: "Récord mundial de la época. Empezaba la era dorada del Nápoles.", en: "World record of its time. The golden era of Napoli was beginning." } },
    { id: "tr_ronaldo_inter", year: 1997, category: "transfer", text: { es: "Ronaldo Nazário ficha por el Inter de Milán", en: "Ronaldo Nazário signs for Inter Milan" }, description: { es: "Desde el Barça por récord mundial. Estaba en su mejor momento.", en: "From Barça for a world record fee. He was at his peak." } },
    { id: "tr_ibra_psg", year: 2012, category: "transfer", text: { es: "Ibrahimovic ficha por el PSG", en: "Ibrahimovic signs for PSG" }, description: { es: "Desde el AC Milan. Lideraría al PSG durante 4 años.", en: "From AC Milan. He would lead PSG for 4 years." } },
    { id: "tr_griezmann_barca", year: 2019, category: "transfer", text: { es: "Griezmann ficha por el Barcelona", en: "Griezmann signs for Barcelona" }, description: { es: "120M€ desde el Atlético tras un año de polémica con su 'La Decisión'.", en: "€120M from Atlético after a year of controversy over his 'La Decisión'." } },
    { id: "tr_lewandowski_barca", year: 2022, category: "transfer", text: { es: "Lewandowski ficha por el Barcelona", en: "Lewandowski signs for Barcelona" }, description: { es: "Desde el Bayern, tras anunciar que no quería renovar.", en: "From Bayern, after announcing he didn't want to renew." } },
    { id: "tr_di_maria_psg", year: 2015, category: "transfer", text: { es: "Di María ficha por el PSG", en: "Di María signs for PSG" }, description: { es: "63M€ desde el Manchester United. Récord mundial para PSG.", en: "€63M from Manchester United. A world record for PSG." } },
    { id: "tr_henry_arsenal", year: 1999, category: "transfer", text: { es: "Thierry Henry ficha por el Arsenal", en: "Thierry Henry signs for Arsenal" }, description: { es: "Desde la Juventus. Wenger lo recupera tras una mala época en Italia.", en: "From Juventus. Wenger rescues him after a bad spell in Italy." } },
    { id: "tr_ronaldinho_barca", year: 2003, category: "transfer", text: { es: "Ronaldinho ficha por el Barcelona", en: "Ronaldinho signs for Barcelona" }, description: { es: "Desde el PSG por 30M€. Empezaba una era mágica del Barça.", en: "From PSG for €30M. A magical era for Barça was beginning." } },
    { id: "tr_torres_chelsea", year: 2011, category: "transfer", text: { es: "Fernando Torres ficha por el Chelsea", en: "Fernando Torres signs for Chelsea" }, description: { es: "50M£ desde el Liverpool. Récord para un fichaje en el fútbol inglés.", en: "£50M from Liverpool. A record signing in English football." } },
    { id: "tr_van_persie_united", year: 2012, category: "transfer", text: { es: "Van Persie ficha por el Manchester United", en: "Van Persie signs for Manchester United" }, description: { es: "Desde el Arsenal. Ferguson conseguiría su última Premier con él.", en: "From Arsenal. Ferguson would win his last Premier League title with him." } },
    { id: "tr_rooney_united", year: 2004, category: "transfer", text: { es: "Rooney ficha por el Manchester United", en: "Rooney signs for Manchester United" }, description: { es: "Con 18 años, desde el Everton por 27M£. Ferguson lo vio como su nueva estrella.", en: "At 18, from Everton for £27M. Ferguson saw him as his new star." } },
    { id: "tr_vinicius_madrid", year: 2018, category: "transfer", text: { es: "Vinicius ficha por el Real Madrid", en: "Vinicius signs for Real Madrid" }, description: { es: "Desde el Flamengo por 45M€. Aún tenía 17 años cuando se firmó la operación.", en: "From Flamengo for €45M. He was still 17 when the deal was signed." } },
    { id: "tr_alexis_arsenal", year: 2014, category: "transfer", text: { es: "Alexis Sánchez ficha por el Arsenal", en: "Alexis Sánchez signs for Arsenal" }, description: { es: "Desde el Barça por 35M€. El chileno se convertiría en estrella en la Premier.", en: "From Barça for €35M. The Chilean would become a Premier League star." } },

    // ==================================================
    // ===== TROFEOS 🏆 (32 eventos) ====================
    // ==================================================
    { id: "tp_argentina_qatar", year: 2022, category: "trophy", text: { es: "Argentina gana el Mundial de Catar", en: "Argentina wins the Qatar World Cup" }, description: { es: "Tercer Mundial para Argentina. Final épica contra Francia (3-3, penaltis).", en: "Third World Cup for Argentina. Epic final against France (3-3, penalties)." } },
    { id: "tp_spain_2010", year: 2010, category: "trophy", text: { es: "España gana su primer Mundial", en: "Spain wins its first World Cup" }, description: { es: "Gol de Iniesta en la prórroga ante Holanda. Sudáfrica 2010.", en: "Iniesta's goal in extra time against the Netherlands. South Africa 2010." } },
    { id: "tp_madrid_decima", year: 2014, category: "trophy", text: { es: "Real Madrid gana 'La Décima'", en: "Real Madrid wins 'La Décima'" }, description: { es: "Décima Champions del Madrid, contra el Atlético en Lisboa.", en: "Madrid's 10th Champions League, against Atlético in Lisbon." } },
    { id: "tp_barca_sextete", year: 2009, category: "trophy", text: { es: "Barcelona gana el sextete", en: "Barcelona wins the sextuple" }, description: { es: "Equipo de Guardiola gana las 6 competiciones de la temporada.", en: "Guardiola's team wins all 6 competitions of the season." } },
    { id: "tp_germany_brazil", year: 2014, category: "trophy", text: { es: "Alemania humilla a Brasil 7-1", en: "Germany humiliates Brazil 7-1" }, description: { es: "Semifinal del Mundial de Brasil. Alemania ganaría el título días después.", en: "Semifinal of the Brazil World Cup. Germany would win the title days later." } },
    { id: "tp_man_city_treble", year: 2023, category: "trophy", text: { es: "Manchester City gana el triplete", en: "Manchester City wins the treble" }, description: { es: "Premier League, FA Cup y Champions League en la misma temporada.", en: "Premier League, FA Cup and Champions League in the same season." } },
    { id: "tp_italia_eurocopa", year: 2021, category: "trophy", text: { es: "Italia gana la Eurocopa en Wembley", en: "Italy wins the Euros at Wembley" }, description: { es: "Italia derrota a Inglaterra en penaltis en su propia casa.", en: "Italy defeats England on penalties in their own home." } },
    { id: "tp_madrid_14", year: 2022, category: "trophy", text: { es: "Real Madrid gana su 14ª Champions", en: "Real Madrid wins its 14th Champions League" }, description: { es: "Tras remontar a PSG, Chelsea y City, vence al Liverpool en París.", en: "After comebacks against PSG, Chelsea and City, they beat Liverpool in Paris." } },
    { id: "tp_brazil_2002", year: 2002, category: "trophy", text: { es: "Brasil gana su 5º Mundial", en: "Brazil wins its 5th World Cup" }, description: { es: "Mundial de Corea-Japón. Ronaldo Nazário marca 8 goles, incluidos los 2 de la final.", en: "Korea-Japan World Cup. Ronaldo Nazário scores 8 goals, including both in the final." } },
    { id: "tp_france_98", year: 1998, category: "trophy", text: { es: "Francia gana su primer Mundial en casa", en: "France wins its first World Cup at home" }, description: { es: "Final 3-0 ante Brasil. Zidane marca dos goles de cabeza.", en: "3-0 final against Brazil. Zidane scores two headers." } },
    { id: "tp_milan_estambul", year: 2005, category: "trophy", text: { es: "Liverpool remonta al Milan en Estambul", en: "Liverpool comes back against Milan in Istanbul" }, description: { es: "El 'Milagro de Estambul'. De 0-3 a 3-3 en 6 minutos. Liverpool gana en penaltis.", en: "The 'Miracle of Istanbul'. From 0-3 to 3-3 in 6 minutes. Liverpool wins on penalties." } },
    { id: "tp_chelsea_munich", year: 2012, category: "trophy", text: { es: "Chelsea gana su primera Champions", en: "Chelsea wins its first Champions League" }, description: { es: "En Múnich contra el Bayern, en su propio estadio. Drogba marca el gol del empate.", en: "In Munich against Bayern, in their own stadium. Drogba scores the equalizer." } },
    { id: "tp_spain_eurocopa_2008", year: 2008, category: "trophy", text: { es: "España gana la Eurocopa de Austria-Suiza", en: "Spain wins the Austria-Switzerland Euros" }, description: { es: "Primer título grande de España en 44 años. Empezaba 'La Roja' dorada.", en: "Spain's first major title in 44 years. The golden 'La Roja' era was beginning." } },
    { id: "tp_germany_2014", year: 2014, category: "trophy", text: { es: "Alemania gana el Mundial de Brasil", en: "Germany wins the Brazil World Cup" }, description: { es: "Götze marca en la prórroga de la final ante Argentina.", en: "Götze scores in extra time of the final against Argentina." } },
    { id: "tp_inter_treble_mou", year: 2010, category: "trophy", text: { es: "Inter de Mourinho gana el triplete", en: "Mourinho's Inter wins the treble" }, description: { es: "Liga, Copa y Champions con el portugués al mando. Eliminaron al Barça en semis.", en: "League, Cup and Champions League with the Portuguese in charge. They knocked out Barça in the semis." } },
    { id: "tp_argentina_copa_america", year: 2021, category: "trophy", text: { es: "Argentina gana la Copa América en Brasil", en: "Argentina wins the Copa América in Brazil" }, description: { es: "Primer título grande para Messi con la albiceleste, 28 años después de la última.", en: "First major title for Messi with the national team, 28 years after the last one." } },
    { id: "tp_real_madrid_15", year: 2024, category: "trophy", text: { es: "Real Madrid gana su 15ª Champions", en: "Real Madrid wins its 15th Champions League" }, description: { es: "Vence al Borussia Dortmund 2-0 en Wembley. Décimo gol de Vinícius en finales.", en: "Defeats Borussia Dortmund 2-0 at Wembley. Vinícius' 10th goal in finals." } },
    { id: "tp_marseille_92", year: 1993, category: "trophy", text: { es: "Marsella gana la primera Champions League", en: "Marseille wins the first Champions League" }, description: { es: "Primer ganador del torneo con su nuevo formato. Vencieron al Milan 1-0.", en: "First winner of the tournament in its new format. They beat Milan 1-0." } },
    { id: "tp_italy_2006", year: 2006, category: "trophy", text: { es: "Italia gana el Mundial de Alemania", en: "Italy wins the Germany World Cup" }, description: { es: "Vence a Francia en penaltis tras la expulsión de Zidane por su cabezazo.", en: "Beats France on penalties after Zidane's expulsion for his headbutt." } },
    { id: "tp_greece_eurocopa", year: 2004, category: "trophy", text: { es: "Grecia gana la Eurocopa de Portugal", en: "Greece wins the Portugal Euros" }, description: { es: "La sorpresa más grande del fútbol europeo. Vence a Portugal 1-0 en la final.", en: "The biggest surprise in European football. Beats Portugal 1-0 in the final." } },
    { id: "tp_spain_eurocopa_2012", year: 2012, category: "trophy", text: { es: "España gana la Eurocopa de Polonia-Ucrania", en: "Spain wins the Poland-Ukraine Euros" }, description: { es: "4-0 a Italia en la final. Tercer título consecutivo de la Roja. Récord histórico.", en: "4-0 against Italy in the final. La Roja's third consecutive title. Historic record." } },
    { id: "tp_barca_wembley_11", year: 2011, category: "trophy", text: { es: "Barcelona gana su 4ª Champions en Wembley", en: "Barcelona wins its 4th Champions League at Wembley" }, description: { es: "3-1 al Manchester United. Ejemplo del mejor Barça de la historia.", en: "3-1 against Manchester United. The best Barça in history at its peak." } },
    { id: "tp_madrid_undecima", year: 2016, category: "trophy", text: { es: "Real Madrid gana 'La Undécima'", en: "Real Madrid wins 'La Undécima'" }, description: { es: "Final de Milán contra el Atlético, ganada en penaltis.", en: "Milan final against Atlético, won on penalties." } },
    { id: "tp_madrid_duodecima", year: 2017, category: "trophy", text: { es: "Real Madrid gana 'La Duodécima'", en: "Real Madrid wins 'La Duodécima'" }, description: { es: "4-1 a la Juventus en Cardiff. Cristiano marca dos goles.", en: "4-1 against Juventus in Cardiff. Cristiano scores two goals." } },
    { id: "tp_madrid_decimotercera", year: 2018, category: "trophy", text: { es: "Real Madrid gana 'La Decimotercera'", en: "Real Madrid wins 'La Decimotercera'" }, description: { es: "3-1 al Liverpool en Kiev. Bale marca un golazo de chilena.", en: "3-1 against Liverpool in Kyiv. Bale scores a stunning bicycle kick." } },
    { id: "tp_argentina_finalissima", year: 2022, category: "trophy", text: { es: "Argentina gana la Finalissima en Wembley", en: "Argentina wins the Finalissima at Wembley" }, description: { es: "3-0 a Italia. Antesala del Mundial de Catar.", en: "3-0 against Italy. Prelude to the Qatar World Cup." } },
    { id: "tp_germany_1990", year: 1990, category: "trophy", text: { es: "Alemania gana el Mundial de Italia", en: "Germany wins the Italy World Cup" }, description: { es: "Vence a Argentina 1-0 con gol de penalti. La 3ª copa para los germanos.", en: "Defeats Argentina 1-0 with a penalty. The 3rd cup for the Germans." } },
    { id: "tp_brazil_94", year: 1994, category: "trophy", text: { es: "Brasil gana el Mundial de Estados Unidos", en: "Brazil wins the United States World Cup" }, description: { es: "Final ante Italia decidida en penaltis. Romário fue el gran protagonista.", en: "Final against Italy decided on penalties. Romário was the main star." } },
    { id: "tp_milan_94", year: 1994, category: "trophy", text: { es: "Milan goleada al Barcelona en final de Champions", en: "Milan thrashes Barcelona in Champions League final" }, description: { es: "4-0 contra el 'Dream Team' de Cruyff. Final de Atenas.", en: "4-0 against Cruyff's 'Dream Team'. Athens final." } },
    { id: "tp_pelé_1970", year: 1970, category: "trophy", text: { es: "Brasil gana el Mundial de México", en: "Brazil wins the Mexico World Cup" }, description: { es: "Tercer Mundial para Pelé. Equipo considerado el mejor de la historia.", en: "Third World Cup for Pelé. Team considered the best in history." } },
    { id: "tp_uruguay_copa_america_2011", year: 2011, category: "trophy", text: { es: "Uruguay gana la Copa América", en: "Uruguay wins the Copa América" }, description: { es: "15ª copa para los charrúas. Récord histórico del torneo.", en: "15th cup for Uruguay. Historic record of the tournament." } },
    { id: "tp_man_united_treble", year: 1999, category: "trophy", text: { es: "Manchester United gana el triplete", en: "Manchester United wins the treble" }, description: { es: "Premier, FA Cup y Champions. Final de Champions épica contra el Bayern.", en: "Premier League, FA Cup and Champions League. Epic Champions League final against Bayern." } },

    // ==================================================
    // ===== DEBUTS 👶 (18 eventos) =====================
    // ==================================================
    { id: "db_messi_barca", year: 2004, category: "debut", text: { es: "Messi debuta con el Barça en Primera", en: "Messi makes his first-team debut for Barça" }, description: { es: "Con 17 años, en un derbi contra el Espanyol. Ya nunca se iría hasta 2021.", en: "At 17, in a derby against Espanyol. He wouldn't leave until 2021." } },
    { id: "db_yamal_barca", year: 2023, category: "debut", text: { es: "Lamine Yamal debuta con el Barça", en: "Lamine Yamal debuts for Barça" }, description: { es: "Con 15 años. El jugador más joven en debutar con el Barça en Liga.", en: "At 15. The youngest player to debut for Barça in La Liga." } },
    { id: "db_pele_brasil", year: 1957, category: "debut", text: { es: "Pelé debuta con la selección brasileña", en: "Pelé debuts for the Brazilian national team" }, description: { es: "Con 16 años. Empezaba la leyenda del Rey del fútbol.", en: "At 16. The legend of the King of Football was beginning." } },
    { id: "db_maradona_argentinos", year: 1976, category: "debut", text: { es: "Maradona debuta en Primera con Argentinos Juniors", en: "Maradona makes his top-flight debut with Argentinos Juniors" }, description: { es: "Diego tenía 15 años. Pronto sería figura del fútbol argentino.", en: "Diego was 15 years old. He would soon become a star of Argentine football." } },
    { id: "db_mbappe_monaco", year: 2015, category: "debut", text: { es: "Mbappé debuta con el Mónaco", en: "Mbappé debuts for Monaco" }, description: { es: "Con 16 años. Dos años después ficharía por el PSG.", en: "At 16. Two years later he would sign for PSG." } },
    { id: "db_cr7_sporting", year: 2002, category: "debut", text: { es: "Cristiano Ronaldo debuta con el Sporting", en: "Cristiano Ronaldo debuts for Sporting" }, description: { es: "Con 17 años. Un año después ficharía por el United.", en: "At 17. A year later he would sign for United." } },
    { id: "db_neymar_santos", year: 2009, category: "debut", text: { es: "Neymar debuta con el Santos", en: "Neymar debuts for Santos" }, description: { es: "Con 17 años. Empezaba la nueva esperanza del fútbol brasileño.", en: "At 17. The new hope of Brazilian football was emerging." } },
    { id: "db_zidane_cannes", year: 1989, category: "debut", text: { es: "Zidane debuta como profesional en el Cannes", en: "Zidane makes his professional debut at Cannes" }, description: { es: "Con 17 años en el club francés. Pronto destacaría en el Burdeos.", en: "At 17 with the French club. He would soon shine at Bordeaux." } },
    { id: "db_iniesta_barca", year: 2002, category: "debut", text: { es: "Iniesta debuta con el Barça en Champions", en: "Iniesta debuts for Barça in the Champions League" }, description: { es: "Con 18 años contra el Brujas. Nadie imaginaba lo que vendría.", en: "At 18 against Club Brugge. No one imagined what was to come." } },
    { id: "db_xavi_barca", year: 1998, category: "debut", text: { es: "Xavi debuta con el primer equipo del Barça", en: "Xavi debuts for the Barça first team" }, description: { es: "Con 18 años. Empezaría una era dorada del centro del campo culé.", en: "At 18. A golden era for Barça's midfield was beginning." } },
    { id: "db_haaland_pro", year: 2016, category: "debut", text: { es: "Haaland debuta como profesional en el Bryne", en: "Haaland makes his professional debut at Bryne" }, description: { es: "El noruego empezaba en su tierra natal antes de ir al Salzburgo y Dortmund.", en: "The Norwegian started in his homeland before going to Salzburg and Dortmund." } },
    { id: "db_endrick_madrid", year: 2024, category: "debut", text: { es: "Endrick debuta con el Real Madrid", en: "Endrick debuts for Real Madrid" }, description: { es: "El joven brasileño llega tras cumplir los 18 años, fichaje cerrado en 2022.", en: "The young Brazilian arrives after turning 18, transfer agreed in 2022." } },
    { id: "db_buffon_parma", year: 1995, category: "debut", text: { es: "Buffon debuta con el Parma", en: "Buffon debuts for Parma" }, description: { es: "Con 17 años contra el Milan. Empezaba la carrera del mejor portero italiano.", en: "At 17 against Milan. The career of the best Italian goalkeeper was beginning." } },
    { id: "db_casillas_madrid", year: 1999, category: "debut", text: { es: "Casillas debuta con el Real Madrid", en: "Casillas debuts for Real Madrid" }, description: { es: "Con 18 años contra el Athletic. Sería el portero del Madrid 16 años.", en: "At 18 against Athletic. He would be Madrid's goalkeeper for 16 years." } },
    { id: "db_owen_liverpool", year: 1997, category: "debut", text: { es: "Michael Owen debuta con el Liverpool", en: "Michael Owen debuts for Liverpool" }, description: { es: "Con 17 años marca su primer gol en su debut.", en: "At 17 he scores his first goal on his debut." } },
    { id: "db_ronaldinho_gremio", year: 1998, category: "debut", text: { es: "Ronaldinho debuta con el Gremio", en: "Ronaldinho debuts for Gremio" }, description: { es: "Con 17 años. La gran esperanza brasileña empezaba en su tierra.", en: "At 17. The great Brazilian hope began in his homeland." } },
    { id: "db_ramos_sevilla", year: 2004, category: "debut", text: { es: "Sergio Ramos debuta con el Sevilla", en: "Sergio Ramos debuts for Sevilla" }, description: { es: "Con 17 años. Un año después se iría al Real Madrid.", en: "At 17. A year later he would move to Real Madrid." } },
    { id: "db_pedri_barca", year: 2020, category: "debut", text: { es: "Pedri debuta con el Barça", en: "Pedri debuts for Barça" }, description: { es: "Con 17 años. Llegaría a ser uno de los mejores centrocampistas del mundo en 2 años.", en: "At 17. He would become one of the best midfielders in the world in 2 years." } },

    // ==================================================
    // ===== RETIRADAS 👋 (16 eventos) ==================
    // ==================================================
    { id: "rt_iniesta_barca", year: 2018, category: "retire", text: { es: "Iniesta deja el Barcelona", en: "Iniesta leaves Barcelona" }, description: { es: "Tras 22 años en el club. Se va al Vissel Kobe de Japón.", en: "After 22 years at the club. He moves to Vissel Kobe in Japan." } },
    { id: "rt_zidane_player", year: 2006, category: "retire", text: { es: "Zidane se retira como jugador", en: "Zidane retires as a player" }, description: { es: "Tras la final del Mundial vs Italia, recordada por su cabezazo a Materazzi.", en: "After the World Cup final vs Italy, remembered for his headbutt on Materazzi." } },
    { id: "rt_buffon_definitive", year: 2023, category: "retire", text: { es: "Buffon se retira definitivamente", en: "Buffon retires for good" }, description: { es: "El portero italiano cuelga las botas a los 45 años en el Parma.", en: "The Italian goalkeeper hangs up his boots at 45 with Parma." } },
    { id: "rt_xavi_barca", year: 2015, category: "retire", text: { es: "Xavi deja el Barcelona", en: "Xavi leaves Barcelona" }, description: { es: "Tras 17 años en el primer equipo. Se va al Al Sadd de Catar.", en: "After 17 years in the first team. He moves to Al Sadd of Qatar." } },
    { id: "rt_pirlo", year: 2017, category: "retire", text: { es: "Andrea Pirlo se retira", en: "Andrea Pirlo retires" }, description: { es: "Tras pasar por Brescia, Inter, Milan, Juventus y New York City FC.", en: "After spells at Brescia, Inter, Milan, Juventus and New York City FC." } },
    { id: "rt_casillas", year: 2020, category: "retire", text: { es: "Iker Casillas se retira", en: "Iker Casillas retires" }, description: { es: "Tras un infarto en 2019, el portero anuncia oficialmente su retirada.", en: "After a heart attack in 2019, the goalkeeper officially announces his retirement." } },
    { id: "rt_puyol", year: 2014, category: "retire", text: { es: "Carles Puyol se retira", en: "Carles Puyol retires" }, description: { es: "Capitán del Barça durante una década, deja el fútbol con 36 años.", en: "Barça's captain for a decade, he leaves football at 36." } },
    { id: "rt_ronaldinho", year: 2018, category: "retire", text: { es: "Ronaldinho anuncia su retirada", en: "Ronaldinho announces his retirement" }, description: { es: "El brasileño confirma su retirada oficial tras varios años inactivo.", en: "The Brazilian confirms his official retirement after several years inactive." } },
    { id: "rt_maldini", year: 2009, category: "retire", text: { es: "Paolo Maldini se retira del Milan", en: "Paolo Maldini retires from Milan" }, description: { es: "Tras 25 temporadas vistiendo de rossonero. Una leyenda del calcio.", en: "After 25 seasons wearing the rossonero shirt. A legend of Italian football." } },
    { id: "rt_totti", year: 2017, category: "retire", text: { es: "Francesco Totti se retira de la Roma", en: "Francesco Totti retires from Roma" }, description: { es: "Toda su carrera en un solo club. 25 años defendiendo a la Roma.", en: "His entire career at a single club. 25 years defending Roma." } },
    { id: "rt_ronaldo_naz", year: 2011, category: "retire", text: { es: "Ronaldo Nazário se retira", en: "Ronaldo Nazário retires" }, description: { es: "Cuelga las botas en el Corinthians a los 34 años por problemas físicos.", en: "He hangs up his boots at Corinthians at 34 due to physical problems." } },
    { id: "rt_gerrard", year: 2016, category: "retire", text: { es: "Steven Gerrard se retira", en: "Steven Gerrard retires" }, description: { es: "Tras pasar por LA Galaxy en sus últimos años. Leyenda del Liverpool.", en: "After spells at LA Galaxy in his final years. A Liverpool legend." } },
    { id: "rt_lampard", year: 2017, category: "retire", text: { es: "Frank Lampard se retira", en: "Frank Lampard retires" }, description: { es: "Tras pasar por Manchester City y New York City FC. Goleador del Chelsea.", en: "After spells at Manchester City and New York City FC. Chelsea's top scorer." } },
    { id: "rt_pele_retire", year: 1977, category: "retire", text: { es: "Pelé se retira definitivamente", en: "Pelé retires for good" }, description: { es: "En el Cosmos de Nueva York. El Rey del fútbol cuelga las botas.", en: "At New York Cosmos. The King of Football hangs up his boots." } },
    { id: "rt_maradona_retire", year: 1997, category: "retire", text: { es: "Maradona se retira como jugador", en: "Maradona retires as a player" }, description: { es: "En Boca Juniors, donde había vuelto. Con 37 años deja el fútbol profesional.", en: "At Boca Juniors, where he had returned. At 37 he leaves professional football." } },
    { id: "rt_cruyff_retire", year: 1984, category: "retire", text: { es: "Johan Cruyff se retira como jugador", en: "Johan Cruyff retires as a player" }, description: { es: "En el Feyenoord. Empezaría su carrera como entrenador del Ajax.", en: "At Feyenoord. He would begin his coaching career at Ajax." } },

    // ==================================================
    // ===== PREMIOS ⭐ (16 eventos) =====================
    // ==================================================
    { id: "aw_messi_8th", year: 2023, category: "award", text: { es: "Messi gana su 8º Balón de Oro", en: "Messi wins his 8th Ballon d'Or" }, description: { es: "Récord histórico del argentino tras ganar el Mundial con Argentina.", en: "Historic record for the Argentinian after winning the World Cup with Argentina." } },
    { id: "aw_cr7_first", year: 2008, category: "award", text: { es: "Cristiano Ronaldo gana su 1er Balón de Oro", en: "Cristiano Ronaldo wins his 1st Ballon d'Or" }, description: { es: "Tras una temporada brillante con el Manchester United.", en: "After a brilliant season with Manchester United." } },
    { id: "aw_messi_first", year: 2009, category: "award", text: { es: "Messi gana su 1er Balón de Oro", en: "Messi wins his 1st Ballon d'Or" }, description: { es: "Tras el sextete del Barça de Guardiola.", en: "After the sextuple with Guardiola's Barça." } },
    { id: "aw_modric_2018", year: 2018, category: "award", text: { es: "Modric gana el Balón de Oro", en: "Modric wins the Ballon d'Or" }, description: { es: "Rompe la hegemonía Messi-Cristiano tras llevar a Croacia a la final del Mundial.", en: "He breaks the Messi-Cristiano hegemony after leading Croatia to the World Cup final." } },
    { id: "aw_rodri_2024", year: 2024, category: "award", text: { es: "Rodri gana el Balón de Oro", en: "Rodri wins the Ballon d'Or" }, description: { es: "El centrocampista del City se impone a Vinicius en una votación polémica.", en: "The City midfielder beats Vinicius in a controversial vote." } },
    { id: "aw_kaka_balon", year: 2007, category: "award", text: { es: "Kaká gana el Balón de Oro", en: "Kaká wins the Ballon d'Or" }, description: { es: "El brasileño rompe el dominio que estaba por venir de Messi y Cristiano.", en: "The Brazilian breaks the dominance that was about to come from Messi and Cristiano." } },
    { id: "aw_benzema_balon", year: 2022, category: "award", text: { es: "Benzema gana el Balón de Oro", en: "Benzema wins the Ballon d'Or" }, description: { es: "Tras una Champions épica con el Madrid, marcando 15 goles en el torneo.", en: "After an epic Champions League with Madrid, scoring 15 goals in the tournament." } },
    { id: "aw_zidane_98", year: 1998, category: "award", text: { es: "Zidane gana su Balón de Oro", en: "Zidane wins his Ballon d'Or" }, description: { es: "Tras ganar el Mundial con Francia. Su único Balón de Oro.", en: "After winning the World Cup with France. His only Ballon d'Or." } },
    { id: "aw_ronaldo_97", year: 1997, category: "award", text: { es: "Ronaldo Nazário gana su 1er Balón de Oro", en: "Ronaldo Nazário wins his 1st Ballon d'Or" }, description: { es: "Con tan sólo 21 años. El más joven en ganarlo durante mucho tiempo.", en: "At just 21 years old. The youngest to win it for a long time." } },
    { id: "aw_yamal_kopa", year: 2024, category: "award", text: { es: "Lamine Yamal gana el Trofeo Kopa", en: "Lamine Yamal wins the Kopa Trophy" }, description: { es: "Premio al mejor jugador joven del año. Con 17 años se convierte en estrella mundial.", en: "Award for best young player of the year. At 17 he becomes a world star." } },
    { id: "aw_figo_balon", year: 2000, category: "award", text: { es: "Figo gana el Balón de Oro", en: "Figo wins the Ballon d'Or" }, description: { es: "El portugués se llevó el premio en su año del fichaje al Real Madrid.", en: "The Portuguese took the award in his year of signing for Real Madrid." } },
    { id: "aw_owen_balon", year: 2001, category: "award", text: { es: "Michael Owen gana el Balón de Oro", en: "Michael Owen wins the Ballon d'Or" }, description: { es: "Tras un año brillante con el Liverpool. El último inglés en ganarlo.", en: "After a brilliant year with Liverpool. The last Englishman to win it." } },
    { id: "aw_ronaldinho_balon", year: 2005, category: "award", text: { es: "Ronaldinho gana el Balón de Oro", en: "Ronaldinho wins the Ballon d'Or" }, description: { es: "El segundo Balón de Oro del brasileño. Estaba en su mejor momento.", en: "The Brazilian's second Ballon d'Or. He was at his peak." } },
    { id: "aw_cannavaro_balon", year: 2006, category: "award", text: { es: "Cannavaro gana el Balón de Oro", en: "Cannavaro wins the Ballon d'Or" }, description: { es: "El primer defensa puro en ganarlo desde Beckenbauer. Tras ganar el Mundial.", en: "The first pure defender to win it since Beckenbauer. After winning the World Cup." } },
    { id: "aw_messi_4_seguidos", year: 2012, category: "award", text: { es: "Messi gana su 4º Balón de Oro consecutivo", en: "Messi wins his 4th consecutive Ballon d'Or" }, description: { es: "Récord histórico nunca igualado. 4 títulos seguidos.", en: "Historic record never equaled. 4 titles in a row." } },
    { id: "aw_ronaldinho_first", year: 2004, category: "award", text: { es: "Ronaldinho gana su 1er Balón de Oro", en: "Ronaldinho wins his 1st Ballon d'Or" }, description: { es: "Tras una temporada mágica con el Barcelona.", en: "After a magical season with Barcelona." } },

    // ==================================================
    // ===== HITOS PERSONALES 🎯 (15 eventos) ===========
    // ==================================================
    { id: "ml_messi_644", year: 2020, category: "milestone", text: { es: "Messi supera el récord de Pelé en un mismo club", en: "Messi breaks Pelé's record at a single club" }, description: { es: "Marca el gol 644 con el Barça, superando los 643 de Pelé en el Santos.", en: "He scores his 644th goal for Barça, surpassing Pelé's 643 at Santos." } },
    { id: "ml_cr7_900", year: 2024, category: "milestone", text: { es: "Cristiano Ronaldo marca su gol 900", en: "Cristiano Ronaldo scores his 900th goal" }, description: { es: "Hito histórico en su carrera. Ningún jugador llegó antes a esa cifra.", en: "Historic milestone in his career. No player had ever reached that figure before." } },
    { id: "ml_buffon_176", year: 2017, category: "milestone", text: { es: "Buffon marca el récord de partidos con Italia (176)", en: "Buffon sets the record for caps with Italy (176)" }, description: { es: "Ningún italiano había vestido la 'azzurra' tantas veces.", en: "No Italian had worn the 'azzurra' shirt so many times." } },
    { id: "ml_iniesta_world_cup_goal", year: 2010, category: "milestone", text: { es: "Iniesta marca el gol del Mundial", en: "Iniesta scores the World Cup-winning goal" }, description: { es: "Minuto 116 de la final ante Holanda. España es campeona por primera vez.", en: "Minute 116 of the final against the Netherlands. Spain becomes champion for the first time." } },
    { id: "ml_messi_91_goals", year: 2012, category: "milestone", text: { es: "Messi marca 91 goles en un año natural", en: "Messi scores 91 goals in a calendar year" }, description: { es: "Récord mundial. Superó los 85 de Gerd Müller de 1972.", en: "World record. He surpassed Gerd Müller's 85 from 1972." } },
    { id: "ml_xavi_1000_passes", year: 2009, category: "milestone", text: { es: "Xavi supera los 1000 pases en una final de Champions", en: "Xavi surpasses 1000 passes in a Champions League final" }, description: { es: "Final ante el United en Roma. Demostración del 'tiki-taka' del Barça.", en: "Final against United in Rome. A showcase of Barça's 'tiki-taka'." } },
    { id: "ml_haaland_36_goals", year: 2023, category: "milestone", text: { es: "Haaland marca 36 goles en una temporada de Premier", en: "Haaland scores 36 goals in a Premier League season" }, description: { es: "Récord histórico de la Premier League en una temporada.", en: "Historic Premier League record in a single season." } },
    { id: "ml_cr7_uefa_top", year: 2014, category: "milestone", text: { es: "Cristiano Ronaldo es máximo goleador histórico de la Champions", en: "Cristiano Ronaldo becomes Champions League all-time top scorer" }, description: { es: "Supera a Messi y a Raúl con su gol 71 en la competición.", en: "He surpasses Messi and Raúl with his 71st goal in the competition." } },
    { id: "ml_messi_500_barca", year: 2017, category: "milestone", text: { es: "Messi alcanza los 500 goles con el Barça", en: "Messi reaches 500 goals for Barça" }, description: { es: "En el clásico contra el Real Madrid en el Bernabéu, ganando 3-2.", en: "In El Clásico against Real Madrid at the Bernabéu, winning 3-2." } },
    { id: "ml_drogba_chelsea_top", year: 2014, category: "milestone", text: { es: "Drogba se convierte en máximo goleador africano del Chelsea", en: "Drogba becomes Chelsea's all-time top African scorer" }, description: { es: "Volvió al club tras dos años fuera. Leyenda de Stamford Bridge.", en: "He returned to the club after two years away. A Stamford Bridge legend." } },
    { id: "ml_mbappe_4_goals_final", year: 2022, category: "milestone", text: { es: "Mbappé marca 3 goles en una final de Mundial", en: "Mbappé scores 3 goals in a World Cup final" }, description: { es: "Hat-trick contra Argentina, primer jugador en lograrlo desde Geoff Hurst en 1966.", en: "Hat-trick against Argentina, first player to do so since Geoff Hurst in 1966." } },
    { id: "ml_pele_1000", year: 1969, category: "milestone", text: { es: "Pelé marca su gol número 1000", en: "Pelé scores his 1000th goal" }, description: { es: "En el Maracaná de Río de Janeiro, contra el Vasco da Gama. Hito del fútbol.", en: "At the Maracanã in Rio de Janeiro, against Vasco da Gama. A football milestone." } },
    { id: "ml_ronaldo_45_la_liga", year: 2015, category: "milestone", text: { es: "Cristiano Ronaldo marca 5 goles en un partido de Liga", en: "Cristiano Ronaldo scores 5 goals in a La Liga match" }, description: { es: "Contra el Granada en el Bernabéu. Récord personal en LaLiga.", en: "Against Granada at the Bernabéu. Personal La Liga record." } },
    { id: "ml_messi_5_champions", year: 2012, category: "milestone", text: { es: "Messi marca 5 goles en un partido de Champions", en: "Messi scores 5 goals in a Champions League match" }, description: { es: "Contra el Bayer Leverkusen en octavos. Récord histórico de la competición.", en: "Against Bayer Leverkusen in the round of 16. Historic record of the competition." } },
    { id: "ml_klose_world_cup_top", year: 2014, category: "milestone", text: { es: "Klose se convierte en máximo goleador histórico de los Mundiales", en: "Klose becomes the all-time top scorer in World Cup history" }, description: { es: "Supera a Ronaldo Nazário con su gol 16 en Mundiales.", en: "He surpasses Ronaldo Nazário with his 16th World Cup goal." } },

    // ==================================================
    // ===== RÉCORDS 📜 (10 eventos) ====================
    // ==================================================
    { id: "rc_invincibles", year: 2004, category: "record", text: { es: "Arsenal completa la temporada invicta", en: "Arsenal completes the season unbeaten" }, description: { es: "Los 'Invincibles' de Wenger ganan la Premier sin perder un partido.", en: "Wenger's 'Invincibles' win the Premier League without losing a match." } },
    { id: "rc_barca_remontada", year: 2017, category: "record", text: { es: "Barcelona remonta 6-1 al PSG", en: "Barcelona comes back 6-1 against PSG" }, description: { es: "Mayor remontada de la historia de Champions tras un 4-0 en la ida.", en: "Biggest comeback in Champions League history after a 4-0 first leg." } },
    { id: "rc_leicester_premier", year: 2016, category: "record", text: { es: "Leicester gana la Premier League", en: "Leicester wins the Premier League" }, description: { es: "El milagro de Ranieri. Leicester había estado en Championship 2 años antes.", en: "Ranieri's miracle. Leicester had been in the Championship 2 years earlier." } },
    { id: "rc_madrid_champions_3_seguidas", year: 2018, category: "record", text: { es: "Real Madrid gana 3 Champions consecutivas", en: "Real Madrid wins 3 consecutive Champions Leagues" }, description: { es: "12ª, 13ª en años consecutivos. Récord histórico en la era moderna del torneo.", en: "12th, 13th in consecutive years. Historic record in the modern era of the tournament." } },
    { id: "rc_city_4_premier_seguidas", year: 2024, category: "record", text: { es: "Manchester City gana 4 Premier consecutivas", en: "Manchester City wins 4 consecutive Premier Leagues" }, description: { es: "Récord histórico de la Premier League. Nadie lo había logrado antes.", en: "Historic Premier League record. No one had achieved it before." } },
    { id: "rc_bayern_11_bundesliga", year: 2023, category: "record", text: { es: "Bayern gana 11 Bundesligas consecutivas", en: "Bayern wins 11 consecutive Bundesligas" }, description: { es: "Récord histórico de las grandes ligas europeas. Hegemonía absoluta.", en: "Historic record among major European leagues. Absolute hegemony." } },
    { id: "rc_psg_4_champions_seguidas", year: 1976, category: "record", text: { es: "Bayern gana 3 Copas de Europa consecutivas", en: "Bayern wins 3 consecutive European Cups" }, description: { es: "El equipo de Beckenbauer y Müller en su mejor momento.", en: "The Beckenbauer and Müller team at its peak." } },
    { id: "rc_real_madrid_5_seguidas", year: 1960, category: "record", text: { es: "Real Madrid gana 5 Copas de Europa consecutivas", en: "Real Madrid wins 5 consecutive European Cups" }, description: { es: "Récord histórico nunca superado. La era de Di Stéfano y Puskas.", en: "Historic record never surpassed. The era of Di Stéfano and Puskas." } },
    { id: "rc_milan_58_invicto", year: 1992, category: "record", text: { es: "Milan completa 58 partidos invicto en Serie A", en: "Milan completes 58 unbeaten matches in Serie A" }, description: { es: "Récord absoluto de la Serie A. Los 'inmortales' de Capello.", en: "Absolute Serie A record. Capello's 'immortals'." } },
    { id: "rc_cr7_5_champions", year: 2018, category: "record", text: { es: "Cristiano Ronaldo gana su 5ª Champions", en: "Cristiano Ronaldo wins his 5th Champions League" }, description: { es: "Récord en la era moderna. La 4ª con el Madrid en 5 años.", en: "Modern-era record. His 4th with Madrid in 5 years." } },

    // ==================================================
    // ===== DRAMA 💔 (15 eventos) ======================
    // ==================================================
    { id: "dr_zidane_headbutt", year: 2006, category: "drama", text: { es: "Zidane le da un cabezazo a Materazzi", en: "Zidane headbutts Materazzi" }, description: { es: "Final del Mundial. Italia ganaría a Francia en penaltis tras la roja a Zidane.", en: "World Cup final. Italy would beat France on penalties after the red card to Zidane." } },
    { id: "dr_maradona_god_hand", year: 1986, category: "drama", text: { es: "Maradona marca con 'la mano de Dios'", en: "Maradona scores with the 'Hand of God'" }, description: { es: "Cuartos del Mundial vs Inglaterra. Minutos después marcaría el gol del siglo.", en: "World Cup quarterfinals vs England. Minutes later he would score the goal of the century." } },
    { id: "dr_eriksen_collapse", year: 2021, category: "drama", text: { es: "Christian Eriksen sufre un paro cardíaco", en: "Christian Eriksen suffers a cardiac arrest" }, description: { es: "En pleno partido de la Eurocopa. Sería reanimado y volvería a jugar al fútbol.", en: "In the middle of a Euros match. He would be resuscitated and return to play football." } },
    { id: "dr_cr7_lesion_eurocopa", year: 2016, category: "drama", text: { es: "Cristiano se lesiona en la final de la Eurocopa", en: "Cristiano gets injured in the Euros final" }, description: { es: "Sale llorando en camilla. Portugal acabaría ganando 1-0 a Francia.", en: "He leaves on a stretcher in tears. Portugal would end up winning 1-0 against France." } },
    { id: "dr_neymar_lesion_brasil", year: 2014, category: "drama", text: { es: "Neymar se lesiona en cuartos del Mundial", en: "Neymar gets injured in the World Cup quarterfinals" }, description: { es: "Tras patada brutal de Zúñiga. Brasil sería humillado 7-1 por Alemania sin él.", en: "After Zúñiga's brutal kick. Brazil would be humiliated 7-1 by Germany without him." } },
    { id: "dr_suarez_mordisco", year: 2014, category: "drama", text: { es: "Suárez muerde a Chiellini en el Mundial", en: "Suárez bites Chiellini at the World Cup" }, description: { es: "Tercer mordisco de su carrera. Suspendido 4 meses por la FIFA.", en: "Third bite of his career. Suspended 4 months by FIFA." } },
    { id: "dr_zidane_red_card", year: 2006, category: "drama", text: { es: "Zidane es expulsado en la final del Mundial", en: "Zidane is sent off in the World Cup final" }, description: { es: "Última jugada de su carrera profesional. Roja directa por el cabezazo.", en: "Final play of his professional career. Straight red for the headbutt." } },
    { id: "dr_henry_handball", year: 2009, category: "drama", text: { es: "Mano de Henry contra Irlanda", en: "Henry's handball against Ireland" }, description: { es: "Permite el gol que clasifica a Francia al Mundial 2010 ante Irlanda.", en: "It allows the goal that qualifies France for the 2010 World Cup against Ireland." } },
    { id: "dr_lampard_no_goal", year: 2010, category: "drama", text: { es: "El gol fantasma de Lampard contra Alemania", en: "Lampard's ghost goal against Germany" }, description: { es: "El balón cruzó claramente la línea pero no fue dado válido. Inglaterra eliminada.", en: "The ball clearly crossed the line but was not given. England eliminated." } },
    { id: "dr_munich_brawl", year: 1990, category: "drama", text: { es: "Maradona pierde la final del Mundial llorando", en: "Maradona loses the World Cup final in tears" }, description: { es: "Argentina cae 1-0 ante Alemania en Roma. Imagen icónica del 10.", en: "Argentina falls 1-0 to Germany in Rome. Iconic image of the number 10." } },
    { id: "dr_pepe_red", year: 2009, category: "drama", text: { es: "Pepe es sancionado 10 partidos por agresión", en: "Pepe is suspended 10 matches for aggression" }, description: { es: "Tras patear a un jugador del Getafe en el suelo. Sanción histórica en LaLiga.", en: "After kicking a Getafe player on the ground. Historic La Liga ban." } },
    { id: "dr_di_canio_push_referee", year: 1998, category: "drama", text: { es: "Di Canio empuja al árbitro y es sancionado", en: "Di Canio pushes the referee and is suspended" }, description: { es: "Le cae una sanción de 11 partidos en la Premier League. Imagen vergonzante.", en: "He gets an 11-match ban in the Premier League. Shameful image." } },
    { id: "dr_keane_haaland_father", year: 2001, category: "drama", text: { es: "Keane lesiona gravemente a Alf-Inge Haaland", en: "Keane seriously injures Alf-Inge Haaland" }, description: { es: "Padre de Erling Haaland. Falta brutal premeditada. Reconocida después por Keane.", en: "Father of Erling Haaland. Brutal premeditated foul. Acknowledged later by Keane." } },
    { id: "dr_real_madrid_eliminado_brujas", year: 1991, category: "drama", text: { es: "Real Madrid eliminado por el Brujas", en: "Real Madrid eliminated by Club Brugge" }, description: { es: "Sorpresa mayúscula. Considerada una de las peores decepciones del Madrid en Europa.", en: "Huge surprise. Considered one of Madrid's worst European disappointments." } },
    { id: "dr_germany_korea_2018", year: 2018, category: "drama", text: { es: "Alemania eliminada en fase de grupos del Mundial", en: "Germany eliminated in the World Cup group stage" }, description: { es: "Pierde 2-0 con Corea del Sur. La vigente campeona se va a casa pronto.", en: "Loses 2-0 to South Korea. The defending champion goes home early." } }

];